web:
  build: .
  command: "bash -c 'vendor/bin/heroku-php-nginx public/'"
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - "8080:8080"
  volumes:
    - ./public:/app/user/public
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - "8080:8080"
  volumes:
    - ".:/app/user"
